<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0S4bZgM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0S4bZgM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0S4bZgM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0S4bZgM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0S4bZgM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0S4bZgM',
    'container.build_id' => '408b4cff',
    'container.build_time' => 1645438032,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0S4bZgM');
