<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRgcieSc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRgcieSc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRgcieSc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRgcieSc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRgcieSc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RgcieSc',
    'container.build_id' => 'c88f9270',
    'container.build_time' => 1645440362,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRgcieSc');
